# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PreventorID' do
  # pod 'PreventorSDK', :path => './PSDK'
  use_frameworks!
end

target 'PreventorSDK' do
  use_frameworks!
  pod 'DocumentReader', '6.6.2753'
  pod 'DocumentReaderFullRFID', '6.6.6999'
end
